
name: 'jaffle_shop'
version: '0.1'
profile: 'crankswagon_sf'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      #materialized: table
      mart: 
        +required_docs: true #https://www.youtube.com/watch?v=eI0rDSJe-9w
        +required_tests: {".*":2}
        +materialized: table
      staging:
        +materialized: view 
